SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS emi_schedule;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS loans;
DROP TABLE IF EXISTS customers;
SET FOREIGN_KEY_CHECKS = 1;
